Add metrics emitter addon
genesis-community/rabbitmq-genesis-kit pull request #2
Opened 2020-09-23 09:23 UTC by bodymindarts

Rebased onto of current master

2020-09-23 15:30 UTC, thomasmitchell requested changes

2020-09-23 15:30 UTC, thomasmitchell commented on kit.yml
> +        certificate: { multiline: true }
This diverged from master, which is my fault. Marking this as it... uh... needs to be re-removed.

2020-09-23 15:30 UTC, thomasmitchell commented on manifests/addons/metrics-emitter.yml
> +          endpoint: (( concat "http://" params.rmq_domain ":15672/api" ))
the management API listens on https 15671, with a kit feature to listen on http 15672 now.

You can use `meta.mgmt_port` to get the port that mgmt is listening on, and `mgmt.mgmt_scheme` to get the url scheme to specify. You'll need to re-rebase off master to get the latter property.

2020-09-23 15:30 UTC, thomasmitchell commented on manifests/addons/metrics-emitter.yml
> +          endpoint: (( concat "http://" params.rmq_domain ":15672/api" ))
To further support talking to the management API, a ca cert option for communicating to the management API would be useful.

2020-09-23 15:30 UTC, thomasmitchell commented on manifests/broker.yml
> +    skip_ssl_validation: true
this should be exposed as a parameter and defaulted to false. for CF APIs that serve signed certs, verifying their contents is good :)

2020-10-01 14:58 UTC, thomasmitchell requested changes

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/addons/broker-tls.yml
> +  - name: broker-registrar
get the current state of this from master please

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/addons/metrics-emitter.yml
> +  cf.deployment_name: (( param "Please specify the deployment name in bosh for CF" ))
give this a default value of `(( concat genesis.env "-cf" ))`

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/addons/metrics-emitter.yml
> +  cf.deployment_name: (( param "Please specify the deployment name in bosh for CF" ))
also, move this, along with the same key in `route_registrar`, to `broker.yml`

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/broker.yml
> +    skip_ssl_validation: true
move this meta line into metrics-emitter.yml, because the broker never actually talks _to_ the CF API, and doesn't care about this.

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/broker.yml
> +    skip_ssl_validation: true
also, make it a `param`

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/addons/metrics-emitter.yml
> +          endpoint: (( concat meta.mgmt_scheme "://" params.rmq_domain ":" meta.mgmt_port "/api" ))
change the domain portion of this to reference `mgmt_domain` instead of `rmq_domain`. They'll usually be the same, but not necessarily.

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/broker.yml
> +            password: (( grab meta.broker.password ))
leave these as they were. These meta properties you're grabbing refer to the authentication to talk to the Broker's API, but they should be the creds to talk to the RabbitMQ as the broker's user for RMQ.

2020-10-01 14:58 UTC, thomasmitchell commented on manifests/server.yml
> +            password: (( grab meta.broker.password ))
leave these as they were. These meta properties you're grabbing refer to the authentication to talk to the Broker's API, but they should be the creds to talk to the RabbitMQ as the broker's user for RMQ.

2020-10-01 14:59 UTC, thomasmitchell commented
also, please document the new feature in `MANUAL.md`

2020-10-01 15:00 UTC, thomasmitchell commented on manifests/addons/broker-tls.yml
> +  - name: broker-registrar
it isn't present in master, somehow got added in here

2020-10-01 15:07 UTC, ramonskie commented on manifests/broker.yml
> +            password: (( grab meta.broker.password ))
i cannot find any changes between master

2020-10-01 15:36 UTC, thomasmitchell commented on manifests/broker.yml
> +            password: (( grab meta.broker.password ))
https://github.com/genesis-community/rabbitmq-genesis-kit/blob/e86d3bf04038e92ca24df9d88245378daeefcd5e/manifests/broker.yml#L75
vs
https://github.com/bodymindarts/rabbitmq-genesis-kit/blob/1bfb9823383f9a96f67b98231dfc5de4734fd78c/manifests/broker.yml#L76

is different

2020-10-02 13:55 UTC, merged